<?php

return [
    'provider' => 'Standard Ebooks',
    'license_name' => 'CC0 1.0 Universal',
    'license_url' => 'https://creativecommons.org/publicdomain/zero/1.0/',
    'catalog' => [
        [
            'identifier' => 'jane-austen_pride-and-prejudice',
            'path' => 'jane-austen/pride-and-prejudice',
            'title' => 'Pride and Prejudice',
            'author' => 'Jane Austen',
            'author_death_year' => 1817,
            'category' => 'Classic Fiction',
            'description' => 'Elizabeth Bennet navigates family expectations, social class, and her changing judgment of Fitzwilliam Darcy.',
        ],
        [
            'identifier' => 'jane-austen_emma',
            'path' => 'jane-austen/emma',
            'title' => 'Emma',
            'author' => 'Jane Austen',
            'author_death_year' => 1817,
            'category' => 'Classic Fiction',
            'description' => 'Emma Woodhouse discovers the limits of her confidence while arranging the romantic lives of those around her.',
        ],
        [
            'identifier' => 'mary-shelley_frankenstein',
            'path' => 'mary-shelley/frankenstein',
            'title' => 'Frankenstein',
            'author' => 'Mary Shelley',
            'author_death_year' => 1851,
            'category' => 'Science Fiction',
            'description' => 'Victor Frankenstein gives life to a creature and faces the consequences of abandoning what he created.',
        ],
        [
            'identifier' => 'bram-stoker_dracula',
            'path' => 'bram-stoker/dracula',
            'title' => 'Dracula',
            'author' => 'Bram Stoker',
            'author_death_year' => 1912,
            'category' => 'Horror',
            'description' => 'A group of friends confronts Count Dracula through journals, letters, and records of their pursuit.',
        ],
        [
            'identifier' => 'oscar-wilde_the-picture-of-dorian-gray',
            'path' => 'oscar-wilde/the-picture-of-dorian-gray',
            'title' => 'The Picture of Dorian Gray',
            'author' => 'Oscar Wilde',
            'author_death_year' => 1900,
            'category' => 'Classic Fiction',
            'description' => 'Dorian Gray remains outwardly young while a hidden portrait records the cost of his choices.',
        ],
        [
            'identifier' => 'h-g-wells_the-time-machine',
            'path' => 'h-g-wells/the-time-machine',
            'title' => 'The Time Machine',
            'author' => 'H. G. Wells',
            'author_death_year' => 1946,
            'category' => 'Science Fiction',
            'description' => 'An inventor travels into the distant future and encounters the divided descendants of humanity.',
        ],
        [
            'identifier' => 'h-g-wells_the-war-of-the-worlds',
            'path' => 'h-g-wells/the-war-of-the-worlds',
            'title' => 'The War of the Worlds',
            'author' => 'H. G. Wells',
            'author_death_year' => 1946,
            'category' => 'Science Fiction',
            'description' => 'A narrator struggles to survive after technologically superior invaders arrive from Mars.',
        ],
        [
            'identifier' => 'arthur-conan-doyle_the-adventures-of-sherlock-holmes',
            'path' => 'arthur-conan-doyle/the-adventures-of-sherlock-holmes',
            'title' => 'The Adventures of Sherlock Holmes',
            'author' => 'Arthur Conan Doyle',
            'author_death_year' => 1930,
            'category' => 'Mystery',
            'description' => 'Dr. Watson records twelve cases solved by the consulting detective Sherlock Holmes.',
        ],
        [
            'identifier' => 'charles-dickens_a-christmas-carol',
            'path' => 'charles-dickens/a-christmas-carol',
            'title' => 'A Christmas Carol',
            'author' => 'Charles Dickens',
            'author_death_year' => 1870,
            'category' => 'Classic Fiction',
            'description' => 'Ebenezer Scrooge is confronted by spirits who reveal the consequences of his cold and isolated life.',
        ],
        [
            'identifier' => 'l-frank-baum_the-wonderful-wizard-of-oz',
            'path' => 'l-frank-baum/the-wonderful-wizard-of-oz',
            'title' => 'The Wonderful Wizard of Oz',
            'author' => 'L. Frank Baum',
            'author_death_year' => 1919,
            'category' => "Children's Literature",
            'description' => 'Dorothy and her companions travel across Oz in search of the wizard who may grant their wishes.',
        ],
    ],
];
