<?php

return [
    'provider' => 'Standard Ebooks',
    'license_name' => 'CC0 1.0 Universal',
    'license_url' => 'https://creativecommons.org/publicdomain/zero/1.0/',
    'authors' => [
        'john-rhode' => ['name' => 'John Rhode', 'death_year' => 1964, 'category' => 'Mystery'],
        'carolyn-wells' => ['name' => 'Carolyn Wells', 'death_year' => 1942, 'category' => 'Mystery'],
        'edgar-rice-burroughs' => ['name' => 'Edgar Rice Burroughs', 'death_year' => 1950, 'category' => 'Adventure'],
        'freeman-wills-crofts' => ['name' => 'Freeman Wills Crofts', 'death_year' => 1957, 'category' => 'Mystery'],
        'arthur-b-reeve' => ['name' => 'Arthur B. Reeve', 'death_year' => 1936, 'category' => 'Mystery'],
        'walter-scott' => ['name' => 'Walter Scott', 'death_year' => 1832, 'category' => 'Classic Fiction'],
        'edgar-wallace' => ['name' => 'Edgar Wallace', 'death_year' => 1932, 'category' => 'Mystery'],
        'r-austin-freeman' => ['name' => 'R. Austin Freeman', 'death_year' => 1943, 'category' => 'Mystery'],
        'anthony-trollope' => ['name' => 'Anthony Trollope', 'death_year' => 1882, 'category' => 'Classic Fiction'],
        'h-rider-haggard' => ['name' => 'H. Rider Haggard', 'death_year' => 1925, 'category' => 'Adventure'],
        'joseph-conrad' => ['name' => 'Joseph Conrad', 'death_year' => 1924, 'category' => 'Classic Fiction'],
        'j-j-connington' => ['name' => 'J. J. Connington', 'death_year' => 1947, 'category' => 'Mystery'],
        'john-buchan' => ['name' => 'John Buchan', 'death_year' => 1940, 'category' => 'Adventure'],
        'thomas-hardy' => ['name' => 'Thomas Hardy', 'death_year' => 1928, 'category' => 'Classic Fiction'],
        'charles-dickens' => ['name' => 'Charles Dickens', 'death_year' => 1870, 'category' => 'Classic Fiction'],
        'arthur-conan-doyle' => ['name' => 'Arthur Conan Doyle', 'death_year' => 1930, 'category' => 'Mystery'],
        'h-g-wells' => ['name' => 'H. G. Wells', 'death_year' => 1946, 'category' => 'Science Fiction'],
        'l-frank-baum' => ['name' => 'L. Frank Baum', 'death_year' => 1919, 'category' => "Children's Literature"],
        'l-m-montgomery' => ['name' => 'L. M. Montgomery', 'death_year' => 1942, 'category' => 'Classic Fiction'],
        'anna-katharine-green' => ['name' => 'Anna Katharine Green', 'death_year' => 1935, 'category' => 'Mystery'],
        'g-k-chesterton' => ['name' => 'G. K. Chesterton', 'death_year' => 1936, 'category' => 'Mystery'],
        'e-nesbit' => ['name' => 'E. Nesbit', 'death_year' => 1924, 'category' => "Children's Literature"],
        'jack-london' => ['name' => 'Jack London', 'death_year' => 1916, 'category' => 'Adventure'],
        'mark-twain' => ['name' => 'Mark Twain', 'death_year' => 1910, 'category' => 'Classic Fiction'],
        'jane-austen' => ['name' => 'Jane Austen', 'death_year' => 1817, 'category' => 'Classic Fiction'],
        'mary-shelley' => ['name' => 'Mary Shelley', 'death_year' => 1851, 'category' => 'Science Fiction'],
        'bram-stoker' => ['name' => 'Bram Stoker', 'death_year' => 1912, 'category' => 'Horror'],
        'oscar-wilde' => ['name' => 'Oscar Wilde', 'death_year' => 1900, 'category' => 'Classic Fiction'],
    ],
    'catalog' => [
        [
            'identifier' => 'jane-austen_pride-and-prejudice',
            'path' => 'jane-austen/pride-and-prejudice',
            'title' => 'Pride and Prejudice',
            'author' => 'Jane Austen',
            'author_death_year' => 1817,
            'category' => 'Classic Fiction',
            'description' => 'Elizabeth Bennet navigates family expectations, social class, and her changing judgment of Fitzwilliam Darcy.',
        ],
        [
            'identifier' => 'jane-austen_emma',
            'path' => 'jane-austen/emma',
            'title' => 'Emma',
            'author' => 'Jane Austen',
            'author_death_year' => 1817,
            'category' => 'Classic Fiction',
            'description' => 'Emma Woodhouse discovers the limits of her confidence while arranging the romantic lives of those around her.',
        ],
        [
            'identifier' => 'mary-shelley_frankenstein',
            'path' => 'mary-shelley/frankenstein',
            'title' => 'Frankenstein',
            'author' => 'Mary Shelley',
            'author_death_year' => 1851,
            'category' => 'Science Fiction',
            'description' => 'Victor Frankenstein gives life to a creature and faces the consequences of abandoning what he created.',
        ],
        [
            'identifier' => 'bram-stoker_dracula',
            'path' => 'bram-stoker/dracula',
            'title' => 'Dracula',
            'author' => 'Bram Stoker',
            'author_death_year' => 1912,
            'category' => 'Horror',
            'description' => 'A group of friends confronts Count Dracula through journals, letters, and records of their pursuit.',
        ],
        [
            'identifier' => 'oscar-wilde_the-picture-of-dorian-gray',
            'path' => 'oscar-wilde/the-picture-of-dorian-gray',
            'title' => 'The Picture of Dorian Gray',
            'author' => 'Oscar Wilde',
            'author_death_year' => 1900,
            'category' => 'Classic Fiction',
            'description' => 'Dorian Gray remains outwardly young while a hidden portrait records the cost of his choices.',
        ],
        [
            'identifier' => 'h-g-wells_the-time-machine',
            'path' => 'h-g-wells/the-time-machine',
            'title' => 'The Time Machine',
            'author' => 'H. G. Wells',
            'author_death_year' => 1946,
            'category' => 'Science Fiction',
            'description' => 'An inventor travels into the distant future and encounters the divided descendants of humanity.',
        ],
        [
            'identifier' => 'h-g-wells_the-war-of-the-worlds',
            'path' => 'h-g-wells/the-war-of-the-worlds',
            'title' => 'The War of the Worlds',
            'author' => 'H. G. Wells',
            'author_death_year' => 1946,
            'category' => 'Science Fiction',
            'description' => 'A narrator struggles to survive after technologically superior invaders arrive from Mars.',
        ],
        [
            'identifier' => 'arthur-conan-doyle_the-adventures-of-sherlock-holmes',
            'path' => 'arthur-conan-doyle/the-adventures-of-sherlock-holmes',
            'title' => 'The Adventures of Sherlock Holmes',
            'author' => 'Arthur Conan Doyle',
            'author_death_year' => 1930,
            'category' => 'Mystery',
            'description' => 'Dr. Watson records twelve cases solved by the consulting detective Sherlock Holmes.',
        ],
        [
            'identifier' => 'charles-dickens_a-christmas-carol',
            'path' => 'charles-dickens/a-christmas-carol',
            'title' => 'A Christmas Carol',
            'author' => 'Charles Dickens',
            'author_death_year' => 1870,
            'category' => 'Classic Fiction',
            'description' => 'Ebenezer Scrooge is confronted by spirits who reveal the consequences of his cold and isolated life.',
        ],
        [
            'identifier' => 'l-frank-baum_the-wonderful-wizard-of-oz',
            'path' => 'l-frank-baum/the-wonderful-wizard-of-oz',
            'title' => 'The Wonderful Wizard of Oz',
            'author' => 'L. Frank Baum',
            'author_death_year' => 1919,
            'category' => "Children's Literature",
            'description' => 'Dorothy and her companions travel across Oz in search of the wizard who may grant their wishes.',
        ],
    ],
];
